package job
// Package job define as tasks Asynq para processamento assíncrono de planilhas.






















































































}	mux.HandleFunc(TypeImportExcel, proc.ProcessTask)func RegisterHandlers(mux *asynq.ServeMux, proc *Processor) {// RegisterHandlers registra os handlers de tasks no Asynq ServeMux.}	return nil	)		zap.Int("errors", len(result.Errors)),		zap.Int("imported", result.Imported),		zap.String("type", string(payload.Type)),	p.logger.Info("Task concluída",	}		return err		)			zap.String("type", string(payload.Type)),			zap.Error(err),		p.logger.Error("Falha no processamento da task",	if err != nil {	})		Type:       payload.Type,		UserID:     payload.UserID,		PropertyID: payload.PropertyID,		FilePath:   payload.FilePath,	result, err := p.pipeline.Run(ctx, pipeline.RunParams{	)		zap.String("property_id", payload.PropertyID),		zap.String("file", payload.FilePath),		zap.String("type", string(payload.Type)),	p.logger.Info("Processando task de import",	}		return fmt.Errorf("falha ao deserializar payload: %w", err)	if err := json.Unmarshal(t.Payload(), &payload); err != nil {	var payload ImportPayloadfunc (p *Processor) ProcessTask(ctx context.Context, t *asynq.Task) error {// ProcessTask é chamado pelo Asynq Server quando uma task chega.}	return &Processor{pipeline: p, logger: logger}func NewProcessor(p *pipeline.Pipeline, logger *zap.Logger) *Processor {// NewProcessor cria um processador de tasks.}	logger   *zap.Logger	pipeline *pipeline.Pipelinetype Processor struct {// Processor processa tasks Asynq usando o pipeline ETL.}	return asynq.NewTask(TypeImportExcel, data, asynq.MaxRetry(3)), nil	}		return nil, fmt.Errorf("falha ao serializar payload: %w", err)	if err != nil {	data, err := json.Marshal(payload)func NewImportTask(payload ImportPayload) (*asynq.Task, error) {// NewImportTask cria uma task Asynq para processamento assíncrono.}	Type       mapper.PipelineType `json:"type"`	UserID     string              `json:"user_id"`	PropertyID string              `json:"property_id"`	FilePath   string              `json:"file_path"`type ImportPayload struct {// ImportPayload é o payload serializado na fila Redis.)	TypeImportExcel = "import:excel"const (// Tipos de tasks Asynq.)	"go.uber.org/zap"	"github.com/jaobarreto/buffs-etl-worker/internal/pipeline"	"github.com/jaobarreto/buffs-etl-worker/internal/mapper"	"github.com/hibiken/asynq"	"fmt"	"encoding/json"	"context"import (package job