package handler




























































































































































































}	return file.WriteTo(c.Response().BodyWriter())	c.Set("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))	c.Set("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")	filename := fmt.Sprintf("%s_%s.xlsx", name, timestamp)	timestamp := time.Now().Format("20060102_150405")func (h *ExportHandler) sendExcel(c *fiber.Ctx, file interface{ WriteTo(w interface{ Write([]byte) (int, error) }) error }, name string) error {}	return params, nil	}		}			params.To = t		if t, err := time.Parse("2006-01-02", to); err == nil {	if to := c.Query("to"); to != "" {	}		}			params.From = t		if t, err := time.Parse("2006-01-02", from); err == nil {	if from := c.Query("from"); from != "" {	}		IncludeRef: c.Query("include_ref", "true") == "true",		Tipo:       c.Query("tipo"),		Sex:        c.Query("sex"),		Maturity:   c.Query("maturity"),		GroupID:    c.Query("group_id"),		PropertyID: propertyID,	params := &exporter.ExportParams{	}		})			Code: "FORBIDDEN", Message: "Sem acesso a esta propriedade",		return nil, c.Status(fiber.StatusForbidden).JSON(dto.ErrorResponse{	if !hasAccess {	}		})			Code: "INTERNAL_ERROR", Message: "Erro interno",		return nil, c.Status(fiber.StatusInternalServerError).JSON(dto.ErrorResponse{		h.logger.Error("Erro ao verificar acesso", zap.Error(err))	if err != nil {	hasAccess, _, err := h.loader.CheckPropertyAccess(c.Context(), userAuthID, propertyID)	userAuthID := middleware.GetUserAuthID(c)	// Verifica acesso	}		})			Code: "MISSING_PROPERTY_ID", Message: "Query param property_id é obrigatório",		return nil, c.Status(fiber.StatusBadRequest).JSON(dto.ErrorResponse{	if propertyID == "" {	propertyID := c.Query("property_id")func (h *ExportHandler) parseExportParams(c *fiber.Ctx) (*exporter.ExportParams, error) {// ── Helpers ─────────────────────────────────────────────────────────────────}	return h.sendExcel(c, file, "template_reproducao")	}		})			Code: "TEMPLATE_ERROR", Message: "Falha ao gerar template",		return c.Status(fiber.StatusInternalServerError).JSON(dto.ErrorResponse{	if err != nil {	file, err := h.exporter.GenerateReproductionTemplate(c.Context(), params.PropertyID, params.IncludeRef)	}		return err	if err != nil {	params, err := h.parseExportParams(c)func (h *ExportHandler) HandleTemplateReproduction(c *fiber.Ctx) error {// HandleTemplateReproduction gera template vazio de reprodução.}	return h.sendExcel(c, file, "template_pesagem")	}		})			Code: "TEMPLATE_ERROR", Message: "Falha ao gerar template",		return c.Status(fiber.StatusInternalServerError).JSON(dto.ErrorResponse{	if err != nil {	file, err := h.exporter.GenerateWeightTemplate(c.Context(), params.PropertyID, params.IncludeRef)	}		return err	if err != nil {	params, err := h.parseExportParams(c)func (h *ExportHandler) HandleTemplateWeight(c *fiber.Ctx) error {// HandleTemplateWeight gera template vazio de pesagem.}	return h.sendExcel(c, file, "template_leite")	}		})			Code: "TEMPLATE_ERROR", Message: "Falha ao gerar template",		return c.Status(fiber.StatusInternalServerError).JSON(dto.ErrorResponse{	if err != nil {	file, err := h.exporter.GenerateMilkTemplate(c.Context(), params.PropertyID, params.IncludeRef)	}		return err	if err != nil {	params, err := h.parseExportParams(c)func (h *ExportHandler) HandleTemplateMilk(c *fiber.Ctx) error {// HandleTemplateMilk gera template vazio de leite.}	return h.sendExcel(c, file, "reproducao")	}		})			Code: "EXPORT_ERROR", Message: "Falha ao gerar planilha de reprodução",		return c.Status(fiber.StatusInternalServerError).JSON(dto.ErrorResponse{		h.logger.Error("Erro ao exportar reprodução", zap.Error(err))	if err != nil {	file, err := h.exporter.ExportReproduction(c.Context(), *params)	}		return err	if err != nil {	params, err := h.parseExportParams(c)func (h *ExportHandler) HandleExportReproduction(c *fiber.Ctx) error {// HandleExportReproduction exporta planilha de reprodução.}	return h.sendExcel(c, file, "pesagem_animal")	}		})			Code: "EXPORT_ERROR", Message: "Falha ao gerar planilha de pesagem",		return c.Status(fiber.StatusInternalServerError).JSON(dto.ErrorResponse{		h.logger.Error("Erro ao exportar pesagem", zap.Error(err))	if err != nil {	file, err := h.exporter.ExportWeight(c.Context(), *params)	}		return err	if err != nil {	params, err := h.parseExportParams(c)func (h *ExportHandler) HandleExportWeight(c *fiber.Ctx) error {// HandleExportWeight exporta planilha de pesagem do animal.}	return h.sendExcel(c, file, "pesagem_leite")	}		})			Code: "EXPORT_ERROR", Message: "Falha ao gerar planilha de leite",		return c.Status(fiber.StatusInternalServerError).JSON(dto.ErrorResponse{		h.logger.Error("Erro ao exportar leite", zap.Error(err))	if err != nil {	file, err := h.exporter.ExportMilk(c.Context(), *params)	}		return err	if err != nil {	params, err := h.parseExportParams(c)func (h *ExportHandler) HandleExportMilk(c *fiber.Ctx) error {// HandleExportMilk exporta planilha de pesagem de leite.}	return &ExportHandler{exporter: exp, loader: l, logger: logger}func NewExportHandler(exp *exporter.Exporter, l *loader.PostgresLoader, logger *zap.Logger) *ExportHandler {// NewExportHandler cria um handler de export.}	logger   *zap.Logger	loader   *loader.PostgresLoader	exporter *exporter.Exportertype ExportHandler struct {// ExportHandler gerencia endpoints de exportação de planilhas.)	"go.uber.org/zap"	"github.com/jaobarreto/buffs-etl-worker/internal/loader"	"github.com/jaobarreto/buffs-etl-worker/internal/http/middleware"	"github.com/jaobarreto/buffs-etl-worker/internal/exporter"	"github.com/jaobarreto/buffs-etl-worker/internal/dto"	"github.com/gofiber/fiber/v2"	"time"	"fmt"import (package handler