package handler






















































































































































































































}	}		return c.Status(fiber.StatusOK).JSON(resp)		}			})				Row: w.Row, Field: w.Field, Value: w.Value, Message: w.Message,			resp.Warnings = append(resp.Warnings, dto.RowIssue{		for _, w := range result.Warnings {		}			})				Row: e.Row, Field: e.Field, Value: e.Value, Message: e.Message,			resp.Errors = append(resp.Errors, dto.RowIssue{		for _, e := range result.Errors {		}			Skipped:  result.Skipped,			Imported: result.Imported,			Total:    result.Total,		resp := dto.ImportResponse{		// Converte domain.ImportResult → dto.ImportResponse		}			})				Message: "Erro interno no processamento",				Code:    "INTERNAL_ERROR",			return c.Status(fiber.StatusInternalServerError).JSON(dto.ErrorResponse{			h.logger.Error("Erro no pipeline", zap.Error(err))			}				})					Message: appErr.Message,					Code:    string(appErr.Code),				return c.Status(appErr.HTTPCode).JSON(dto.ErrorResponse{			if appErr, ok := err.(*apperror.AppError); ok {		if err != nil {		defer os.Remove(filePath)		// Remove arquivo temporário após processamento		})			Type:       pipelineType,			UserID:     userID,			PropertyID: propertyID,			FilePath:   filePath,		result, err := h.pipeline.Run(c.Context(), pipeline.RunParams{		// 9. Processamento síncrono		}			})				Status:  "PROCESSING",				Message: fmt.Sprintf("Planilha com %d linhas enviada para processamento assíncrono", rowCount),				JobID:   jobID,			return c.Status(fiber.StatusAccepted).JSON(dto.AsyncImportResponse{			)				zap.Int("rows", rowCount),				zap.String("job_id", jobID),			h.logger.Info("Import enfileirado como job assíncrono",			}				})					Message: "Falha ao enfileirar processamento assíncrono",					Code:    "INTERNAL_ERROR",				return c.Status(fiber.StatusInternalServerError).JSON(dto.ErrorResponse{				h.logger.Error("Falha ao enfileirar task", zap.Error(err))				os.Remove(filePath)			if err != nil {			_, err = h.asynqClient.Enqueue(task, asynq.TaskID(jobID))			}				})					Message: "Falha ao criar task assíncrona",					Code:    "INTERNAL_ERROR",				return c.Status(fiber.StatusInternalServerError).JSON(dto.ErrorResponse{				os.Remove(filePath)			if err != nil {			})				Type:       pipelineType,				UserID:     userID,				PropertyID: propertyID,				FilePath:   filePath,			task, err := job.NewImportTask(job.ImportPayload{			jobID := uuid.New().String()		if rowCount > h.cfg.Worker.AsyncThreshold {		// 8. Processamento assíncrono para arquivos grandes		}			})				Message: "Não foi possível ler o arquivo Excel",				Code:    string(apperror.CodeFileCorrupted),			return c.Status(fiber.StatusBadRequest).JSON(dto.ErrorResponse{			os.Remove(filePath)		if err != nil {		rowCount, err := extractor.RowCount(filePath)		// 7. Verifica número de linhas para decidir sync vs async		}			})				Message: "Falha ao salvar arquivo temporário",				Code:    "INTERNAL_ERROR",			return c.Status(fiber.StatusInternalServerError).JSON(dto.ErrorResponse{			h.logger.Error("Falha ao salvar arquivo", zap.Error(err))		if err := c.SaveFile(file, filePath); err != nil {		filePath := filepath.Join(h.cfg.Upload.TempDir, fileName)		fileName := fmt.Sprintf("%s_%d%s", propertyID, time.Now().UnixMilli(), ext)		os.MkdirAll(h.cfg.Upload.TempDir, 0755)		// 6. Salva em disco temporário		}			})				Message: "Apenas arquivos .xlsx e .xls são aceitos",				Code:    string(apperror.CodeInvalidFormat),			return c.Status(fiber.StatusBadRequest).JSON(dto.ErrorResponse{		if ext != ".xlsx" && ext != ".xls" {		ext := filepath.Ext(file.Filename)		// 5. Valida extensão		}			})				Message: fmt.Sprintf("Arquivo excede o limite de %dMB", h.cfg.Upload.MaxFileSize/(1024*1024)),				Code:    string(apperror.CodeFileTooLarge),			return c.Status(fiber.StatusBadRequest).JSON(dto.ErrorResponse{		if file.Size > h.cfg.Upload.MaxFileSize {		// 4. Valida tamanho		}			})				Message: "Arquivo Excel não enviado. Use multipart/form-data com campo 'file'.",				Code:    "MISSING_FILE",			return c.Status(fiber.StatusBadRequest).JSON(dto.ErrorResponse{		if err != nil {		file, err := c.FormFile("file")		// 3. Recebe o arquivo		}			})				Message: "Sem acesso a esta propriedade",				Code:    "FORBIDDEN",			return c.Status(fiber.StatusForbidden).JSON(dto.ErrorResponse{		if !hasAccess {		}			})				Message: "Erro interno ao verificar permissões",				Code:    "INTERNAL_ERROR",			return c.Status(fiber.StatusInternalServerError).JSON(dto.ErrorResponse{			h.logger.Error("Erro ao verificar acesso à propriedade", zap.Error(err))		if err != nil {		hasAccess, userID, err := h.loader.CheckPropertyAccess(c.Context(), userAuthID, propertyID)		userAuthID := middleware.GetUserAuthID(c)		// 2. Verifica acesso à propriedade		}			})				Message: "Query param property_id é obrigatório",				Code:    "MISSING_PROPERTY_ID",			return c.Status(fiber.StatusBadRequest).JSON(dto.ErrorResponse{		if propertyID == "" {		propertyID := c.Query("property_id")		// 1. Valida property_id	return func(c *fiber.Ctx) error {func (h *ImportHandler) HandleImport(pipelineType mapper.PipelineType) fiber.Handler {// Se o arquivo tiver mais linhas que o threshold, enfileira como job assíncrono.// HandleImport processa o upload e importação de uma planilha Excel.}	}		logger:      logger,		cfg:         cfg,		asynqClient: ac,		loader:      l,		pipeline:    p,	return &ImportHandler{) *ImportHandler {	logger *zap.Logger,	cfg *config.Config,	ac *asynq.Client,	l *loader.PostgresLoader,	p *pipeline.Pipeline,func NewImportHandler(// NewImportHandler cria um handler de import com todas as dependências.}	logger      *zap.Logger	cfg         *config.Config	asynqClient *asynq.Client	loader      *loader.PostgresLoader	pipeline    *pipeline.Pipelinetype ImportHandler struct {// ImportHandler gerencia endpoints de importação de planilhas.)	"go.uber.org/zap"	"github.com/jaobarreto/buffs-etl-worker/pkg/apperror"	"github.com/jaobarreto/buffs-etl-worker/internal/pipeline"	"github.com/jaobarreto/buffs-etl-worker/internal/mapper"	"github.com/jaobarreto/buffs-etl-worker/internal/loader"	"github.com/jaobarreto/buffs-etl-worker/internal/job"	"github.com/jaobarreto/buffs-etl-worker/internal/http/middleware"	"github.com/jaobarreto/buffs-etl-worker/internal/extractor"	"github.com/jaobarreto/buffs-etl-worker/internal/dto"	"github.com/jaobarreto/buffs-etl-worker/internal/config"	"github.com/hibiken/asynq"	"github.com/google/uuid"	"github.com/gofiber/fiber/v2"	"time"	"path/filepath"	"os"	"fmt"import (package handler// Package handler contém os handlers HTTP do ETL BUFFS.