package dto






































































}	Services map[string]string `json:"services"`	Status   string            `json:"status"`type HealthResponse struct {// HealthResponse é a resposta do healthcheck.// ── Health DTOs ─────────────────────────────────────────────────────────────}	Message string `json:"message"`	Code    string `json:"code"`type ErrorResponse struct {// ErrorResponse é a resposta padrão de erro.// ── Error DTOs ──────────────────────────────────────────────────────────────}	Progress int    `json:"progress,omitempty"`	Status   string `json:"status"`	JobID    string `json:"job_id"`type JobStatusResponse struct {// JobStatusResponse é a resposta do endpoint de status de job.// ── Job DTOs ────────────────────────────────────────────────────────────────}	IncludeRef *bool     `query:"include_ref"`	Tipo       string    `query:"tipo"`	To         time.Time `query:"to"`	From       time.Time `query:"from"`	Sex        string    `query:"sex"`	Maturity   string    `query:"maturity"`	GroupID    string    `query:"group_id"`	PropertyID string    `query:"property_id"`type ExportQuery struct {// ExportQuery contém os parâmetros de filtro para exportação.// ── Export DTOs ─────────────────────────────────────────────────────────────}	Status  string `json:"status"`	Message string `json:"message"`	JobID   string `json:"job_id"`type AsyncImportResponse struct {// AsyncImportResponse é retornado quando o import é enfileirado (202).}	Message string `json:"message"`	Value   string `json:"value"`	Field   string `json:"field"`	Row     int    `json:"row"`type RowIssue struct {// RowIssue representa um erro ou warning de uma linha.}	Warnings []RowIssue `json:"warnings"`	Errors   []RowIssue `json:"errors"`	Skipped  int        `json:"skipped"`	Imported int        `json:"imported"`	Total    int        `json:"total_rows"`	JobID    string     `json:"job_id,omitempty"`type ImportResponse struct {// ImportResponse é a resposta de um import (síncrono ou assíncrono).// ── Import DTOs ─────────────────────────────────────────────────────────────import "time"package dto// Package dto contém os Request/Response DTOs para os endpoints HTTP.